# Generated by Django 5.1.3 on 2024-11-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=255)),
                ('driver_number', models.CharField(max_length=20)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
