# Generated by Django 5.1.3 on 2024-11-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busentry',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='busentry',
            name='driver_number',
        ),
    ]
